### PR TITLE
Blog and other updates

### PR DESCRIPTION
**Pull request by brentvatne**
Hi @bradediger @jordanbyron

The blog layout/styles are pretty much done, although I did not implement any pagination or filtering/sorting, that's something that we can do when the need arises.

I thought it would be nice to have the blog use a slightly different theme from the rest of the site (although the design of the main site is still in flux), so I used the colors from the logo and I think it looks quite nice.

Suggestions welcome for anything, in particular:
- Blog name
- Subtitle for the blog name to describe it
- Short description of Madriska to put at the end of each blog page
- Links or text I'm missing from the footer

Also, you'll notice in one of the screenshots that the "k" is a bit weird. The junction font seems to behave badly when in bold on Chrome - this does not occur in other browsers.

blog1
blog2
blog4
blog5
blog6

### CODE REVIEW

**Comment by bradediger** [comment]
Nice progress! My initial comments:
- The colors and layout are awesome. The [responsive design](http://dressresponsively.com/shirt/3) works really well, and the tag styles and footer are nice and tight.
- I'm not crazy about the "Madriska Memos" name or the handwriting font in the subtitle. Let's shop that around a little more.
- In general, we're going with "Madriska Inc." or just "Madriska" in preference to "Madriska Media Group" (which remains our legal name). We started out doing a lot more design work than we currently do, but haven't bothered to change the name yet.

I like it. :zap: 
Brad

**Comment by brentvatne** [comment]
> The colors and layout are awesome. The responsive design works really well, and the tag styles and footer are nice and tight.

Glad you like it!

> I'm not crazy about the "Madriska Memos" name or the handwriting font in the subtitle. Let's shop that around a little more.

I completely agree about the name, just picked one of the first things that came to my mind.

> In general, we're going with "Madriska Inc." or just "Madriska" in preference to "Madriska Media Group" (which remains our legal name). We started out doing a lot more design work than we currently do, but haven't bothered to change the name yet.

Good to know!

**Comment by brentvatne** [comment]
Forgot to include a screenshot of the syntax highlighting

syntax

**Comment by jordanbyron** [comment]
@brentvatne wow nice job. I'm really impressed with both the blog and some of the changed you made to the rest of the site. 

So the blog name / tagline is going to be hard to come up with. Branding is a bitch :wink: 

> Short description of Madriska to put at the end of each blog page

acking the whole project for "Media Group" is probably a good idea. @bradediger do you prefer just "Madriska" or do you want to throw in the "Inc."? Personally, I like just plain old Madriska unless you are doing something like a copyright. 

As for the description maybe we could do something with less synergy :smiley: I like keeping things short and sweet. 

> [Madriska](http://madriska.com) is a software-development company that is great at what they do so that you can be great at what you do. 

Links or text missing from the footer:

Copyright, RSS feed, Authors

I'd also try carrying that footer throughout the site.

**Comment by brentvatne** [comment]
> @brentvatne wow nice job. I'm really impressed with both the blog and some of the changed you made to the rest of the site.

:joy:

I haven't looked much at the actual site yet though, just changed the link style, dropped the footer, and converted it to use the foundation responsive layout. Before I move on to that I'm going to cleanup `layouts/default.html` - if you looked at it you would notice it's become a bit of a mess with conditionals. Any suggestions on the overall site are certainly welcome!

> As for the description maybe we could do something with less synergy  I like keeping things short and sweet.

Bahaha

> Links or text missing from the footer:
> 
> Copyright, RSS feed, Authors

Sounds good. Do you think it's worth adding an RSS feed? I personally haven't used RSS in over two years.

> I'd also try carrying that footer throughout the site.

Good call.

Thanks for the comments guys.

**Comment by jordanbyron** [comment]
> Sounds good. Do you think it's worth adding an RSS feed? I personally haven't used RSS in over two years.

I still use RSS and it's damn simple for us to add to jekyl so my vote is :+1: 

> Before I move on to that I'm going to cleanup layouts/default.html

Good call. We can probably just create separate layouts for the public site and blog. That should clean things up a lot.

**Pull request closed without merging**
